services:
  - type: web
    name: real-estate-ai-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run postinstall
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
    disk:
      name: cache
      mountPath: /opt/render/.cache
      sizeGB: 1 